### PR TITLE
Secure Bloomlibrary.org upload with the use of a new book function (BL-12568)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: 14 of 20 files reviewed, all discussions resolved

___
*[`package.json` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSgr48BT1rF-Pdab_T:-NhSoY1e-EC9LeM2ksEF:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/package.json#L17)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I don't think we need this now?
</blockquote></details>

Done.
___
*[`book/function.json` line 1 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSi0N75dWFVYEtPD6H:-NhSvslqEO6RvC3nHWIB:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/book/function.json#L1)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's add a README.md file in the book folder which similar high-level information like opds'.
Mostly url format, what goes in the body of the request, etc.
</blockquote></details>

Done.
___
*[`book/uploadFinish.ts` line 82 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSnOTl94sIt1mllta3:-NhSo_ix0BNaPjYHz_lZ:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/book/uploadFinish.ts#L82)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

appropriately

(sorry, that was my typo)
</blockquote></details>

Done.
___
*[`common/BloomParseServer.ts` line 72 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhShsda6Myx1eAQNE7D:-NhSoVPi1QsKSa35YRvC:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/common/BloomParseServer.ts#L72)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like we don't need this?
If we do, we need to document it in a README.
</blockquote></details>

Done.
___
*[`common/s3.ts` line 14 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSlhx1Cq4-JBqIh5zn:-NhSooN93tyjqwpzM5RC:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/common/s3.ts#L14)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's put all the imports together above the consts.
</blockquote></details>

Done.
___
*[`common/s3.ts` line 47 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSm1_Q7B0PrUPPH5fu:-NhSp3Hh6LLiVv-4X5QM:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/common/s3.ts#L47)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Probably deserves a comment about why we need the loop and continuation token.

Here and in delete
</blockquote></details>

Done.
___
*[`common/s3.ts` line 172 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhSmxGX87cQwOhbAqsB:-NhSpCcNDkkdGQ5Qrj3K:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/688068fdaf794e43f0e3e42cc5094f31cfd9e22b/common/s3.ts#L172)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> testTemporaryCredentialsName

Is there a better name for this?
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: all files reviewed, 1 unresolved discussion

___
*[`book/uploadStart.ts` line 95 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTF27O7fVqTr-NmOW8:-NhTF27PA43BScvRs8no:bj43qan) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/eecc599f397dbc7ba8710ab21c77cc2d96f7536e/book/uploadStart.ts#L95)):*
> ```XML
>         existingBookPath,
>         env
>       );
> ```

One call passes the bookObjectId, and the other passes a path.
Seems like one must be wrong?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: 19 of 20 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`book/uploadStart.ts` line 95 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTF27O7fVqTr-NmOW8:-NhTK3z92qrDlQNb63V5:b-2m99wh) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/eecc599f397dbc7ba8710ab21c77cc2d96f7536e/book/uploadStart.ts#L95)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

One call passes the bookObjectId, and the other passes a path.
Seems like one must be wrong?
</blockquote></details>

The first argument is the s3 prefix, we want to list all books with that prefix. The first call is to get all the files for this book, which would all have the bookObjectId as the prefix. But then we need to make sure not to delete the files which are currently being used, so I exclude all files with the prefix from the current baseUrl. I added some comments

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`book/uploadStart.ts` line 95 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTF27O7fVqTr-NmOW8:-NhTMkt34O-1s_X2JLju:b-i6lth7) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/eecc599f397dbc7ba8710ab21c77cc2d96f7536e/book/uploadStart.ts#L95)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

The first argument is the s3 prefix, we want to list all books with that prefix. The first call is to get all the files for this book, which would all have the bookObjectId as the prefix. But then we need to make sure not to delete the files which are currently being used, so I exclude all files with the prefix from the current baseUrl. I added some comments
</blockquote></details>

Yes, of course. Thanks.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`bookCleanup/function.json` line 13 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhU-ERHAIsmkRjh9GE5:-NhU-ERHAIsmkRjh9GE6:bzaddjm) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/function.json#L13)):*
> ```JSON
>   ],
>   "scriptFile": "../dist/bookCleanup/index.js"
> }
> ```

I'm leaning toward leaving this as a separate function from dailyTimer as you have it.

Let's have it run at least an hour different from that or contentfulToCrowdin.
And maybe add comments in all three places we have a schedule indicating what runs when?
___
*[`bookCleanup/index.ts` line 6 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTzaHT99MbasO9uWXn:-NhTzaHT99MbasO9uWXo:b-24avre) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/index.ts#L6)):*
> ```XML
> import { Environment } from "../common/utils";
> 
> const runEvenIfLocal: boolean = false;
> ```

Let's implement or remove this.
___
*[`bookCleanup/index.ts` line 24 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTylq1D9BuN39PExGn:-NhTylq1D9BuN39PExGo:b-sroacg) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/index.ts#L24)):*
> ```XML
>     context.log("book cleanup succeeded");
>   } catch (e) {
>     context.log("book cleanup failed", e);
> ```

What are the pros/cons of catching and logging vs letting this error?
I suppose you probably just copied this from our existing code. That's fine.
___
*[`common/BloomParseServer.ts` line 309 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTxqts0n5gkth8cjDQ:-NhTxqts0n5gkth8cjDR:b-t8s6k6) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/common/BloomParseServer.ts#L309)):*
> ```XML
>   }
> 
>   public static getBooks(where: string, onlyOne = false): Promise<any> {
> ```

I think I would prefer to have a separate `getBook(where)` which calls `getBooks(where, true)`.
The callers just don't seem clear enough that it is only getting one record. And the lack of type-checking just makes it worse.
___
*[`common/BloomParseServer.ts` line 362 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTyOsvC4Ai30Ctx451:-NhTyOsvC4Ai30Ctx452:b-r53is9) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/common/BloomParseServer.ts#L362)):*
> ```XML
> 
>   // This Azure function logs in to the Parse server, using a hard-coded user name ("book-cleanup").
>   // That account has a ParseServer "role" which is allows it to delete the old unfinished uploads from the books table.
> ```

which allows it to
OR
which is allowed to



_Suggestion:_
```XML
which is allows it to
```

**Review by nabalone — COMMENTED** [review]
> Reviewed 3 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: 17 of 24 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`bookCleanup/function.json` line 13 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhU-ERHAIsmkRjh9GE5:-NhbhqNh4Sw1H7YTdCf-:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/function.json#L13)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm leaning toward leaving this as a separate function from dailyTimer as you have it.

Let's have it run at least an hour different from that or contentfulToCrowdin.
And maybe add comments in all three places we have a schedule indicating what runs when?
</blockquote></details>

Done
___
*[`bookCleanup/index.ts` line 6 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTzaHT99MbasO9uWXn:-NhbiN_58eF0IOorR6co:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/index.ts#L6)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's implement or remove this.
</blockquote></details>

Done
___
*[`bookCleanup/index.ts` line 24 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTylq1D9BuN39PExGn:-NhbiYuQBPJRb4CM7Grn:b-nqd2u7) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/bookCleanup/index.ts#L24)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What are the pros/cons of catching and logging vs letting this error?
I suppose you probably just copied this from our existing code. That's fine.
</blockquote></details>

Yes probably, though really I was catching and logging so I didn't have to restart my local server every time something failed during local development
___
*[`common/BloomParseServer.ts` line 309 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTxqts0n5gkth8cjDQ:-NhcNEOo8qdQTua-4EqC:blpmr75) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/common/BloomParseServer.ts#L309)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think I would prefer to have a separate `getBook(where)` which calls `getBooks(where, true)`.
The callers just don't seem clear enough that it is only getting one record. And the lack of type-checking just makes it worse.
</blockquote></details>

Done. Though still wondering if my `if (onlyOne) ` is not the best way to design this method
___
*[`common/BloomParseServer.ts` line 362 at r5](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NhTyOsvC4Ai30Ctx451:-NhcNXiNEZzmw5ku6abP:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/081abbb24ce2b87e4f1d332cea4cb0b6677a2bf9/common/BloomParseServer.ts#L362)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

which allows it to
OR
which is allowed to
</blockquote></details>

Done

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 4 of 4 files at r6, 6 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 6 files at r8, 1 of 4 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: 23 of 27 files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`common/BloomParseServer.ts` line 369 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifbqSF9cV9cQ-UkwpG:-NifbqSF9cV9cQ-UkwpH:bsvo9hp) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/BloomParseServer.ts#L369)):*
> ```XML
>     return await BloomParseServer.loginAsUser(
>       "book-cleanup",
>       process.env["bloomParseServerBookCleanupPassword"]
> ```

I think we ended up with different passwords per environment.
Do we need to make them the same?
Or should we have 3 diff env vars?

I would lean toward the latter since this does need to be fairly secure.
___
*[`common/s3.ts` line 204 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifdUxH7xNRRG-Ac9be:-NifdUxIC2l-YO9pLYsl:b214b6w) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/s3.ts#L204)):*
> ```XML
> }
> 
> export function getS3Client() {
> ```

Looks like you don't need to export this.
___
*[`common/utils.ts` line 10 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifcADQDwieZa_84Sxf:-NifcADQDwieZa_84Sxg:betyzlw) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/utils.ts#L10)):*
> ```XML
> }
> // For testing and development, we prefer to use the parse table associated with the development Bloom Library.
> // For production, we need to use the parse table associated with the production Bloom Library.
> ```

I think the extra line should be before the comment, not after.

However...
I'm not sure I see much value in the comment. I know you copied it from the first place this enum was defined.
But it now has a third option. And it just seems unnecessary to me.

Thoughts?

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 6 files at r8, 3 of 4 files at r9.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: all files reviewed, 5 unresolved discussions (waiting on @nabalone)

___
*[`common/BloomParseServer.test.ts` line 63 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifqG__CWTA6Yk3vDF7:-NifqG__CWTA6Yk3vDF8:b87attp) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/BloomParseServer.test.ts#L63)):*
> ```XML
>       newBookRecord.uploadPendingTimestamp
>     );
>     expect(book.uploadPendingTimestamp).not.toBeFalsy(); // we should have put an uploadPendingTimestamp so we can test clearing it below
> ```

Isn't this line redundant?
I.e. you just checked that it equaled newBookRecord.uploadPendingTimestamp.
___
*[`common/s3.test.ts` line 174 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-Nifo4NHAX8WrsZ48Fzl:-Nifo4NHAX8WrsZ48Fzm:b-80floz) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/s3.test.ts#L174)):*
> ```XML
> });
> 
> // TODO test plan should include a line involving books with over 1000 files
> ```

Let's move this TODO from here to the card.

**Review by nabalone — COMMENTED** [review]
Should I be adding PR descriptions like this ^^ when I open the PR? Just as a general review comment? Or how do I enter it? 

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-:-NikmMCI050gPCwLpWPp:b-nxjnpa)* status: 21 of 27 files reviewed, 2 unresolved discussions (waiting on @andrew-polk)

___
*[`common/BloomParseServer.ts` line 369 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifbqSF9cV9cQ-UkwpG:-Niki_4qCPaage7h29n6:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/BloomParseServer.ts#L369)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think we ended up with different passwords per environment.
Do we need to make them the same?
Or should we have 3 diff env vars?

I would lean toward the latter since this does need to be fairly secure.
</blockquote></details>

Done
___
*[`common/BloomParseServer.test.ts` line 63 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifqG__CWTA6Yk3vDF7:-NikigmX-7E7vCcPgZHj:b-vketq4) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/BloomParseServer.test.ts#L63)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Isn't this line redundant?
I.e. you just checked that it equaled newBookRecord.uploadPendingTimestamp.
</blockquote></details>

I just wanted to make sure we did in fact put an uploadPendingTimestamp in earlier so we can really test removing it, but that's hardcoded anyway so I'll just remove this line
___
*[`common/s3.ts` line 204 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifdUxH7xNRRG-Ac9be:-Nikio5n5axvlbr164z0:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/s3.ts#L204)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Looks like you don't need to export this.
</blockquote></details>

Done
___
*[`common/s3.test.ts` line 174 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-Nifo4NHAX8WrsZ48Fzl:-Nikm-hX9aRii8qNeUdn:bb6un1j) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/s3.test.ts#L174)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's move this TODO from here to the card.
</blockquote></details>

Done
___
*[`common/utils.ts` line 10 at r9](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NifcADQDwieZa_84Sxf:-Nikm7nh4i3onA3OKqmg:b-b14gdj) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/80b91a399d0cb1a3522608b39eb5681f6d153aca/common/utils.ts#L10)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think the extra line should be before the comment, not after.

However...
I'm not sure I see much value in the comment. I know you copied it from the first place this enum was defined.
But it now has a third option. And it just seems unnecessary to me.

Thoughts?
</blockquote></details>

I agree that this comment seems unnecessary. Removed

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`README.md` line 49 at r10](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64#-NilGwsB4SbfRe8sVTeK:-NilGwsB4SbfRe8sVTeL:bp56q6t) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/0abb51d3b6e51fcbef7a2aca318b58ccd4376713/README.md#L49)):*
> ```Markdown
> The bookCleanup function also requires the password for the book-cleanup users to be in the following environment variables: `bloomParseServerProdBookCleanupPassword` for prod, `bloomParseServerDevBookCleanupPassword` for dev and `bloomParseServerUnitTestBookCleanupPassword` for unit tests.
> 
> The opds function also requires the password for the `catalog-service` user in the environment variable `bloomParseServerCatalogServicePassword`.
> ```

This opds-specific one is already detailed in the opds readme.

I suppose we should have a new bookcleanup readme with our specific ones. Or maybe since there isn't much to say, the section below is sufficient (as opposed to another file)?


Then maybe we add a comment here explaining that some functions also require other env vars? And to see the function-specific notes/readmes?

I don't know. I'm up for whatever makes sense. But consistency is usually helpful. Except when it isn't... : )
But we probably shouldn't have the same comment about bookCleanup env vars in two places. That just means we'll miss one place if we need to update it.

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/64)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
