### PR TITLE
Implement the new API design

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75)* status: 2 of 15 files reviewed, 1 unresolved discussion

___
*[`api-spec.yml` line 1 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqdzf1z8_VxgsvuwYjV:-Nqdzf1z8_VxgsvuwYjW:be2hbbj) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/960bf85800531f09fca6388aa820bbf8879ac7aa/api-spec.yml#L1)):*
> ```YAML
> openapi: 3.0.3
> ```

You can generally ignore this file. JH is reviewing it independently.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
A few minor points.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-:-Nqn74Mo-lBVL2pbAz7Y:bhy8lf8)* status: 1 of 17 files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`books/utils.test.ts` line 20 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn6jWL6xD8kpn9PEz9:-Nqn6jWMEK3_j9fG6GDK:b-qwmw6z) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/utils.test.ts#L20)):*
> ```XML
>     const result = getIdAndAction("123:action");
>     expect(result).toEqual(["123", "action"]);
>   });
> ```

Worth a test like ":delete" that is missing the ID but has an action?
What should happen if there is a list of IDs? (I haven't looked all through the code, but we want to be sure they can't do something to someone else's book by passing a list with first a book they have permissions on, then another where they don't. Most likely, passing a list of IDs where only one is expected will just fail.)
___
*[`books/index.ts` line 35 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn0S9V6tpdRPP0Zmob:-Nqn0S9V6tpdRPP0Zmoc:b9ir7ws) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L35)):*
> ```XML
>     if (!action) {
>       // Query for a specific book
>       // TODO: implement
> ```

Is this expected to continue with the following code, or will it return from this block? If the latter, might be good to put at least that in now. And is there a simple way we can return a code signifying "not implemented" until we do?
___
*[`books/index.ts` line 95 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn1MH06NbLeXJNjV1k:-Nqn1MH06NbLeXJNjV1l:b-tpjs2w) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L95)):*
> ```XML
>     context.res = {
>       status: 200,
>       body: { results: bookRecords, count },
> ```

It feels odd that we're returning book records in a case where the number of records is known to have been limited to zero. But of course we know it's an empty array, so pretty harmless. Still it might be worth commenting that bookRecords will always be empty?
___
*[`books/index.ts` line 102 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn41Dc2SIf5plckLXn:-Nqn41Dc2SIf5plckLXo:b21jrt8) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L102)):*
> ```XML
>   // General query for books... not implemented yet
>   context.res = {
>     status: 200,
> ```

I discovered there is a specific error (501) for "not implemented) so maybe use that for now? But from the description it's not really meant for such cases, so maybe just a generic 500?
___
*[`books/index.ts` line 125 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn5ExO0sZ9Y8sLU_bP:-Nqn5ExO0sZ9Y8sLU_bQ:byjs28d) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L125)):*
> ```XML
>   // but we use POST when the url might be too long for a GET request.
> 
>   if (action) return true;
> ```

And otherwise return false? Seems odd to have one branch without a return at all; I'm surprised typescript allowed it.
___
*[`book/uploadStart.ts` line 96 at r4](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn-GqDDwnTzd3D65_y:-Nqn-GqDDwnTzd3D65_z:b-fwxa30) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/af99f91071d0185a6287755d99913dfe17c378b2/book/uploadStart.ts#L96)):*
> ```XML
>   const currentTime = Date.now();
> 
>   const isNewBook = bookObjectId === undefined;
> ```

Should we do some sort of validation if they claim to have provided an existing book ID? Will it fail reasonably cleanly if it is NOT (e.g., if we got an empty string, or a comma-separated list of IDs, or a random string that does not match any book)?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75)* status: 1 of 18 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`books/utils.test.ts` line 20 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn6jWL6xD8kpn9PEz9:-NqnbCBEBz4uPw0VIkK6:b-koautl) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/utils.test.ts#L20)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Worth a test like ":delete" that is missing the ID but has an action?
What should happen if there is a list of IDs? (I haven't looked all through the code, but we want to be sure they can't do something to someone else's book by passing a list with first a book they have permissions on, then another where they don't. Most likely, passing a list of IDs where only one is expected will just fail.)
</blockquote></details>

Added the test (and subsequently improved the code!).

I think the current cases probably would have handled an invalid id ok, but I went ahead and made an explicit, upfront check which will handle future cases, too.
___
*[`books/index.ts` line 35 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn0S9V6tpdRPP0Zmob:-NqnZeRzE2TKp6LWMZgY:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L35)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Is this expected to continue with the following code, or will it return from this block? If the latter, might be good to put at least that in now. And is there a simple way we can return a code signifying "not implemented" until we do?
</blockquote></details>

Done.
___
*[`books/index.ts` line 95 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn1MH06NbLeXJNjV1k:-Nqn_4fgEroBoM2vfKCz:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L95)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It feels odd that we're returning book records in a case where the number of records is known to have been limited to zero. But of course we know it's an empty array, so pretty harmless. Still it might be worth commenting that bookRecords will always be empty?
</blockquote></details>

Done.
___
*[`books/index.ts` line 102 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn41Dc2SIf5plckLXn:-NqnZgZB4bUpUPurNyti:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L102)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I discovered there is a specific error (501) for "not implemented) so maybe use that for now? But from the description it's not really meant for such cases, so maybe just a generic 500?
</blockquote></details>

Done.
___
*[`books/index.ts` line 125 at r6](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn5ExO0sZ9Y8sLU_bP:-NqnFIUMEoPbOTbxrGqy:b-louicu) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1800764b2e64b1d683ce585f96c2da81993a8b62/books/index.ts#L125)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

And otherwise return false? Seems odd to have one branch without a return at all; I'm surprised typescript allowed it.
</blockquote></details>

Oops. Yes, I am surprised this didn't get flagged.
I added an eslint warning. I considered error, but there are some others already and they weren't obvious what we wanted to do with them.
___
*[`book/uploadStart.ts` line 96 at r4](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-Nqn-GqDDwnTzd3D65_y:-Nqn_CrlBVBrUnbC0Gnh:b-so75ko) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/af99f91071d0185a6287755d99913dfe17c378b2/book/uploadStart.ts#L96)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Should we do some sort of validation if they claim to have provided an existing book ID? Will it fail reasonably cleanly if it is NOT (e.g., if we got an empty string, or a comma-separated list of IDs, or a random string that does not match any book)?
</blockquote></details>

We've validated it isn't empty above.

If it isn't "new", we will look it up in the database below (`getBookInfoByObjectId(bookId)`) which will fail and throw a 400.

**Review by JohnThomson — APPROVED** [review]
:lgtm: I think I've looked at everything except the file you said JohnH was dealing with.

> Reviewed 1 of 3 files at r1, 11 of 15 files at r4, 2 of 6 files at r7.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/75#-:-NqnkOi_7vOrAD1FnnVp:b-xf4fj5)* status: 6 of 18 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

**Pull request merged**
