### PR TITLE
Make development easier

### PR DESCRIPTION
**Pull request by andrew-polk**
* Don't do anything in timer functions by default when running locally
* Update README.md

---
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30)* status: 0 of 5 files reviewed, all discussions resolved

___
*[common/bookinfo.ts, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30#-ModkvSC8gA-DLIAEelM:-ModkvSC8gA-DLIAEelN:bqcqiqj) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/65a979041a481c3cd567005b8ba3cfaa73b31c36/common/bookinfo.ts#L52)):*
> ```XML
>       case BookInfoSource.PRODUCTION:
>       default:
>         return "R6qNTeumQXjJCMutAJYAwPtip1qBulkFyLefkCE5";
> ```

These are already committed in other public repos and are not secret, so having them as environment variable is just an unnecessary barrier to development.

**Review by JohnThomson — APPROVED** [review]
LGTM with one minor suggestion. But I don't know this code at all (does anyone but you?)

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30#-:-Modm3X-BTdNhuet9RZZ:b-p1prqb)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[contentfulToCrowdin/index.ts, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30#-Modlqrv4zBmHKQ2cHag:-Modlqrw0_GjI4RIStJC:bo07nni) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/65a979041a481c3cd567005b8ba3cfaa73b31c36/contentfulToCrowdin/index.ts#L37)):*
> ```XML
> async function readTransformUpload() {
>   // By default, we don't want to run this if we are running the functions locally.
>   // Typically, if we are running locally, we want to test some other function, not this one.
> ```

As in the other case, it would be helpful to state any particular reason why it's not good to run it unnecessarily.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[contentfulToCrowdin/index.ts, line 37 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30#-Modlqrv4zBmHKQ2cHag:-Modr1Dr1FQyM8VChies:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/65a979041a481c3cd567005b8ba3cfaa73b31c36/contentfulToCrowdin/index.ts#L37)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

As in the other case, it would be helpful to state any particular reason why it's not good to run it unnecessarily.
</blockquote></details>

Done.
___
*[common/bookinfo.ts, line 52 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30#-ModkvSC8gA-DLIAEelM:-Modr5OI-qS2n7Y90z4H:bd3ts17) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/65a979041a481c3cd567005b8ba3cfaa73b31c36/common/bookinfo.ts#L52)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

These are already committed in other public repos and are not secret, so having them as environment variable is just an unnecessary barrier to development.
</blockquote></details>

JH asked me to back this out.

**Review by JohnThomson — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/30)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
