### PR TITLE
Implement check for book permissions (BL-12726)

### PR DESCRIPTION
**Pull request by andrew-polk**
Check Contentful for collection-level upload permissions

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)

### CODE REVIEW

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`common/BloomParseServer.ts` line 580 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2ADjH4Fjl7qrxbrOW:-Nr2ADjH4Fjl7qrxbrOX:b-4r9ml3) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L580)):*
> ```XML
>     // In theory, we could write more generic code to handle more use cases.
>     // (And basically duplicate much of the logic in BloomLibrary2's LibraryQueryHooks.ts.)
>     // But for now, these two (tag and brandingProjectName) should handle all the cases we need.
> ```

That is, because all the collections that we want to list as collections that certain users are allowed to edit are in fact defined in one of these ways? Might be worth spelling out a bit more.
___
*[`common/BloomParseServer.ts` line 602 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2AahdDTVryDwVS7Ax:-Nr2AahdDTVryDwVS7Ay:b5wvque) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L602)):*
> ```XML
>           return true;
>         }
>       }
> ```

Feels like we should somehow raise an alarm if the collection is not, after all, defined in one of the ways we can deal with.
___
*[`common/contentful.ts` line 24 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr27Ou-Ee8K_wdoBgis:-Nr27Ou-Ee8K_wdoBgit:b-g1x56z) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L24)):*
> ```XML
>   const collectionResponse = await client.getEntries({
>     content_type: "collection",
>     "fields.localization[ne]": "No",
> ```

I don't remember (and can't guess) what putting this strange property into the object does, so I think a comment might be helpful. (Also in a couple of other similar queries).
___
*[`common/contentful.ts` line 75 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr29AN-5AROhxhTvCo8:-Nr29AN-5AROhxhTvCo9:bv4e5kf) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L75)):*
> ```XML
>   emailAddress: string
> ) {
>   const filters = new Set<IContentfulCollectionFilter>();
> ```

How about collectionDefiningFilters? To make it a bit clearer how the filters are related to the collections. (For example, they are not filters used to decide which users can edit the collections.)
___
*[`common/contentful.ts` line 88 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28YFaAVz4_ybR5mm6:-Nr28YFaAVz4_ybR5mm7:bvtpvga) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L88)):*
> ```XML
> }
> 
> function processCollection(
> ```

How about "collectFilters"? The current name doesn't much suggest what kind of processing we're doing. Maybe a comment, too...it's a bit confusing that we're using the "collector" pattern, the source we're collecting from is a collection, and the object we're collecting data into is (of course) one too.
___
*[`common/contentful.ts` line 98 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28PL11cuKkaaq7WOB:-Nr28PL11cuKkaaq7WOC:bn8mvs0) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L98)):*
> ```XML
>   if (collection.fields.childCollections) {
>     collection.fields.childCollections.forEach((childCollection) => {
>       processCollection(childCollection, filters);
> ```

Are you quite sure childCollections can't loop?
___
*[`contentfulToCrowdin/index.ts` line 82 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr29epl1Rf5hsCQ34nK:-Nr29epl1Rf5hsCQ34nL:b-v20u3r) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/contentfulToCrowdin/index.ts#L82)):*
> ```XML
>   let valid = true;
>   if (!validateContentfulEnvironmentVariables()) {
>     console.error("unable to run contentfulToCrowdin.");
> ```

I think these messages (and some comments) need updating, now that we're using these functions for another purpose (besides updating Crowdin). (Or maybe we're not, and you're just improving some unrelated code, or refactoring?)

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)* status: all files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`common/BloomParseServer.ts` line 580 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2ADjH4Fjl7qrxbrOW:-Nr6voaRB6dqkld4orLj:bp0pmsv) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L580)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

That is, because all the collections that we want to list as collections that certain users are allowed to edit are in fact defined in one of these ways? Might be worth spelling out a bit more.
</blockquote></details>

See if that's clear enough.
___
*[`common/BloomParseServer.ts` line 602 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2AahdDTVryDwVS7Ax:-Nr2HTuiAdARyJBcY7pp:b-mczbhm) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L602)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Feels like we should somehow raise an alarm if the collection is not, after all, defined in one of the ways we can deal with.
</blockquote></details>

That's a good thought... but there are at least two issues:
1. We would be getting constant noise from such alarms. We plan to set moderators to have access to the root collection, which means every filter in contentful can/will be hit for moderators (until we return true).
    - Hm. I just realized we should probably have a special case for root access to shortcut things. After all, that will probably be at least the 50% use case once we have to actually start looking at filters. So maybe my `#1` issue isn't an issue.
        - In addition, I just realized that I don't think every book is necessarily part of a collection which is in a descendant collection from root.
2. I don't know how/where to raise such an alarm.

In practice, I expect the collections we use for this purpose will always be defined using one of the filter types above.
If the librarian adds one which isn't, and a user is expecting to gain super-user permissions, we will find out right away and be able to either tweak the filter or this code.

Definitely happy to discuss more.
___
*[`common/contentful.ts` line 24 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr27Ou-Ee8K_wdoBgis:-Nr2GUv20d5BSsMrBHVb:bat0lxl) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L24)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't remember (and can't guess) what putting this strange property into the object does, so I think a comment might be helpful. (Also in a couple of other similar queries).
</blockquote></details>

I'm just moving this from its prior location in contentfulToCrowdin. 
If I understood it, I would take this opportunity to add a comment. But I don't, either. : )
___
*[`common/contentful.ts` line 75 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr29AN-5AROhxhTvCo8:-Nr6eG1c0Ev3aGt1QcNN:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L75)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about collectionDefiningFilters? To make it a bit clearer how the filters are related to the collections. (For example, they are not filters used to decide which users can edit the collections.)
</blockquote></details>

Done.
___
*[`common/contentful.ts` line 88 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28YFaAVz4_ybR5mm6:-Nr6e2Ot8bm69-Gk9AQe:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L88)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How about "collectFilters"? The current name doesn't much suggest what kind of processing we're doing. Maybe a comment, too...it's a bit confusing that we're using the "collector" pattern, the source we're collecting from is a collection, and the object we're collecting data into is (of course) one too.
</blockquote></details>

Done.
___
*[`common/contentful.ts` line 98 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28PL11cuKkaaq7WOB:-Nr6e1S49aIlrJbjZPW6:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L98)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Are you quite sure childCollections can't loop?
</blockquote></details>

Done.
___
*[`contentfulToCrowdin/index.ts` line 82 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr29epl1Rf5hsCQ34nK:-Nr2G-tC8lfosL2ejQhJ:b-rnkuu5) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/contentfulToCrowdin/index.ts#L82)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think these messages (and some comments) need updating, now that we're using these functions for another purpose (besides updating Crowdin). (Or maybe we're not, and you're just improving some unrelated code, or refactoring?)
</blockquote></details>

I'm just pulling some stuff out of this `contentfulToCrowdin` function into a common file to hold all the contentful stuff (contentful.ts).
So, this error remained here, specific to this context. There is another error message in `validateContentfulEnvironmentVariables` which is more general.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`common/BloomParseServer.ts` line 580 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2ADjH4Fjl7qrxbrOW:-Nr7gsTv8na66QahmFy4:b-eyjl4m) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L580)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

See if that's clear enough.
</blockquote></details>

I think what I was looking for is something like you said below:
"We expect the collections we use for this purpose will always be defined using one of the filter types above"
Maybe here, "We expect the collections we list super-users for will always be defined using one of these two  (tag and brandingProjectName)".
If we put a super-user on some other collection it will fail immediately and be easy to debug.
___
*[`common/contentful.ts` line 88 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28YFaAVz4_ybR5mm6:-Nr7iVgHAvSPCU5wJjGy:b-jxliss) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L88)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Since we need another pass, I might just suggest adding "into the "filters" collection" 
___
*[`common/contentful.ts` line 98 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28PL11cuKkaaq7WOB:-Nr7iLoD488ocRVIY0R_:b-m1nkn0) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L98)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think to achieve the goal you need to pass depth+1 to the recursive call.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @JohnThomson)

___
*[`common/BloomParseServer.ts` line 580 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr2ADjH4Fjl7qrxbrOW:-NrBTL_B0SVbcbPiAWFz:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/BloomParseServer.ts#L580)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think what I was looking for is something like you said below:
"We expect the collections we use for this purpose will always be defined using one of the filter types above"
Maybe here, "We expect the collections we list super-users for will always be defined using one of these two  (tag and brandingProjectName)".
If we put a super-user on some other collection it will fail immediately and be easy to debug.
</blockquote></details>

Done.
___
*[`common/contentful.ts` line 88 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28YFaAVz4_ybR5mm6:-NrBJMbjDeUu2VGnVy16:bbqsnx3) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L88)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Since we need another pass, I might just suggest adding "into the "filters" collection"
</blockquote></details>

Done.
Used set rather than collection to reduce one layer of ambiguity.
___
*[`common/contentful.ts` line 98 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76#-Nr28PL11cuKkaaq7WOB:-NrBHKuz2BYW4biZzvSO:b-4sc5t6) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/1237aa547abdf19bc9341cf4fee6535221d04083/common/contentful.ts#L98)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I think to achieve the goal you need to pass depth+1 to the recursive call.
</blockquote></details>

Ha. Oops.
Thanks.

**Review by JohnThomson — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/76)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

**Pull request merged**
