### PR TITLE
Modify API to allow for long-running actions (BL-12568)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 19 of 19 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69)* status: all files reviewed, 11 unresolved discussions (waiting on @andrew-polk)

___
*[`README.md` line 109 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9RM9t2OpTxwhgwrHW:-Nl9RM9t2OpTxwhgwrHX:b-p7f6bc) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/README.md#L109)):*
> ```Markdown
> ## Caching
> 
> For just the `harvest/` path, if the path begins with "thumbnails", we return a Cache-Control of 1 year.
> ```

This needs explanation. Why would we not want a client to see a new thumbnail if a new version of the book is uploaded with a different cover image?
___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9S4tC2MUxVWpFMHCl:-Nl9S4tC2MUxVWpFMHCm:bjaomaf) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/README.md#L134)):*
> ```Markdown
> - **img**=URL - This is an optional URL to a (preferably) 300x300 thumbnail image of the book or bookshelf. Harvester creates this as `thumbnail-300x300.png`. Our other thumbnail files don't constrain both height and width and can end up with one side less than 200px which Facebook won't display.
> - **width**=number - Image width, in pixels. Defaults to 256.
> - **height**=number - Image height, in pixels. Defaults to 256.
> ```

Why default to 256 if we prefer 300?
___
*[`book/README.md` line 27 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9TIpfEXwtqWZbyPcK:-Nl9TIpfEXwtqWZbyPcL:ba4p8uw) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/README.md#L27)):*
> ```Markdown
> ### upload-start (POST)
> 
> Gets everything ready for a client to begin uploading book files.
> ```

I find it surprising that these functions need to be long-running. Maybe it would be helpful to explain in each function? For example, I can imagine that upload-finish takes a long time because files are being copied from a temporary location to a final one. I can't even guess a possible reason for upload-start to be long-running.
___
*[`book/README.md` line 42 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9SpG5-N7Htl2h5cSs:-Nl9SpG5-N7Htl2h5cSt:b-gbb9xj) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/README.md#L42)):*
> ```Markdown
> ```
> {
>     url: <S3 parent "folder" where book files will be uploaded; does not include book title>,
> ```

Aren't we trying to hide the fact that we're using S3? Maybe not...I don't see any API for actually uploading the files.
___
*[`book/uploadFinish.ts` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9HX3G3Bz7tp10iESM:-Nl9HX3G3Bz7tp10iESN:b-1u99lq) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L17)):*
> ```XML
> } from "../longRunningActions/utils";
> 
> export async function handleUploadFinish(
> ```

I'm not clear what UploadFinish is or what it means to handle it. I think a major exported function deserves a comment. I'm guessing that this is handling the request to upload a book (maybe the last of several API calls involved in the upload process?) Or maybe it's involved in what happens when the upload is finished and we're ready to tell the client on the next ping?
___
*[`book/uploadFinish.ts` line 53 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9Fw7l2FF2AH2GPJ87:-Nl9Fw7l2FF2AH2GPJ88:buxbjv6) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L53)):*
> ```XML
>   );
> 
>   context.res = createAcceptedResponse(instanceId, req.url);
> ```

I wondered what a 'res' might be...'resource' was the first thing that came to mind. If this is a type we control, I would suggest not abbreviating 'response'.
The name 'createAcceptedResponse' does not help me much, so some comment here might be helpful. Are we creating some object of type AcceptedResponse, or hoping for a response indicating that a Create request was accepted, or...?
From our verbal discussions I'm guessing this contains the URL to ping to find out whether the long-running upload is finished, and that this is the response that ends up going to the client that initiated the upload. That's probably worth documenting.
___
*[`book/uploadFinish.ts` line 70 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9J3c27-nArepB3W58:-Nl9J3c27-nArepB3W59:b-evxqzv) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L70)):*
> ```XML
> 
>   const bookInfo = await parseServer.getBookInfoByObjectId(bookId);
>   if (!BloomParseServer.canModifyBook(userInfo, bookInfo)) {
> ```

Feels too late to be handling permission errors after we uploaded the whole book. Could we fail faster somehow?
___
*[`book/uploadStart.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9U1sA9y1eihTqiYJw:-Nl9U1sA9y1eihTqiYJx:bnghw4x) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadStart.ts#L21)):*
> ```XML
> const kPendingString = "pending";
> 
> export async function handleUploadStart(
> ```

In my ignorance of all this, one thing that threw me for a long time is that we have two layers of long-running-ness. There are two long-running API calls (upload-start and upload-finish) and then the even longer-running process that happens in between, when we're uploading the files. I first came at this expecting that uploadStart was about initializing a long-running task called Upload, and uploadFinish was about when that long-running task was finished. But actually, each of them initiates a long-running task whose termination is detected by calling the status API. I think a comment on this function, and perhaps at least a cross-reference at the start of handleUploadFinish, would be very helpful for someone coming at this code the first time.
___
*[`book/uploadStart.ts` line 106 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9KN_q7cgzkfueGWkh:-Nl9KN_q7cgzkfueGWki:b-6a1r73) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadStart.ts#L106)):*
> ```XML
>     );
> 
>     // If another upload of this book has been started but not finished, delete its files
> ```

Are you thinking that an earlier upload attempt failed, or trying to handle the case that the same account is trying to upload the same book from two computers at the same time?
I suppose what we're deleting is files in a holding area? We're not going to interfere with the previous upload until we have a complete one?
___
*[`status/README.md` line 10 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9P3Uv2eca19KFAwy9:-Nl9P3Uv2eca19KFAwyA:b5y3s6f) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/status/README.md#L10)):*
> ```Markdown
> https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#post-or-delete-lro-pattern
> and
> https://github.com/microsoft/api-guidelines/blob/vNext/azure/ConsiderationsForServiceDesign.md#long-running-operations.
> ```

These guidelines say "A long-running POST should not be used for resource create". Does that mean we should be using PUT instead of POST when a book is uploaded for the first time?
___
*[`status/README.md` line 58 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9P__q1ebw7moQ8TRz:-Nl9P__q1ebw7moQ8TS-:b5owbki) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/status/README.md#L58)):*
> ```Markdown
> ```
> 
> Note, there are other statuses we have not yet implemented ("NotStarted", "Running", "Canceled"). But it would probably be good for clients to handle "Canceled" as a terminal status along with "Succeeded" and "Failed".
> ```

I find it very surprising that we don't use a response indicating that the long-running task is still running.

**Review by andrew-polk — COMMENTED** [review]
More coming, but pushing what I have so far.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-:-NlAZ-YbEUAJtDhtiSoE:bf7lvms)* status: 15 of 19 files reviewed, 11 unresolved discussions (waiting on @JohnThomson)

___
*[`README.md` line 109 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9RM9t2OpTxwhgwrHW:-NlAWV6E7Oow-9REMXg0:blwy7e1) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/README.md#L109)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This needs explanation. Why would we not want a client to see a new thumbnail if a new version of the book is uploaded with a different cover image?
</blockquote></details>

Sorry, I have no idea.
This has been around a few years.
___
*[`README.md` line 134 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9S4tC2MUxVWpFMHCl:-NlAWPoVCnJpuBFc_AO3:biwl3co) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/README.md#L134)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Why default to 256 if we prefer 300?
</blockquote></details>

Sorry; I have no idea.
This has been around a few years.
___
*[`book/README.md` line 42 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9SpG5-N7Htl2h5cSs:-NlAW4bxCXU1RxQJm0ag:b-bn3spr) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/README.md#L42)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Aren't we trying to hide the fact that we're using S3? Maybe not...I don't see any API for actually uploading the files.
</blockquote></details>

Not at this point, no. We did discuss it, but it was too much to attempt. 
The client handles uploading the files to S3 between uploadStart and uploadFinish.
___
*[`book/uploadFinish.ts` line 53 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9Fw7l2FF2AH2GPJ87:-NlAYFLfBTFfx_SCNC4A:b-3i28i2) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L53)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I wondered what a 'res' might be...'resource' was the first thing that came to mind. If this is a type we control, I would suggest not abbreviating 'response'.
The name 'createAcceptedResponse' does not help me much, so some comment here might be helpful. Are we creating some object of type AcceptedResponse, or hoping for a response indicating that a Create request was accepted, or...?
From our verbal discussions I'm guessing this contains the URL to ping to find out whether the long-running upload is finished, and that this is the response that ends up going to the client that initiated the upload. That's probably worth documenting.
</blockquote></details>

Sorry, no, we don't control "res".

Does the createAcceptedResponse rename help enough? Or it still needs comments?
___
*[`book/uploadFinish.ts` line 70 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9J3c27-nArepB3W58:-NlAVvDZ6FRpEGeJx3F4:becagc0) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L70)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Feels too late to be handling permission errors after we uploaded the whole book. Could we fail faster somehow?
</blockquote></details>

We also do this check during uploadStart.
But we have to check again to make sure they provided valid credentials again.
___
*[`status/README.md` line 58 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9P__q1ebw7moQ8TRz:-NlAWb8b98f2WkWIbfFk:b-n9vvmn) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/status/README.md#L58)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I find it very surprising that we don't use a response indicating that the long-running task is still running.
</blockquote></details>

Oops. Yes, it does.

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69)* status: 15 of 19 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

___
*[`book/README.md` line 27 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9TIpfEXwtqWZbyPcK:-NliqLEZBDghPuxDNT8S:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/README.md#L27)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I find it surprising that these functions need to be long-running. Maybe it would be helpful to explain in each function? For example, I can imagine that upload-finish takes a long time because files are being copied from a temporary location to a final one. I can't even guess a possible reason for upload-start to be long-running.
</blockquote></details>

Done.
___
*[`book/uploadFinish.ts` line 17 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9HX3G3Bz7tp10iESM:-NliqNkx9YTxrDoiO2Sx:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadFinish.ts#L17)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not clear what UploadFinish is or what it means to handle it. I think a major exported function deserves a comment. I'm guessing that this is handling the request to upload a book (maybe the last of several API calls involved in the upload process?) Or maybe it's involved in what happens when the upload is finished and we're ready to tell the client on the next ping?
</blockquote></details>

Done.
___
*[`book/uploadStart.ts` line 21 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9U1sA9y1eihTqiYJw:-NliqU3B2EInNfCWPEUa:b-ljbmsa) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadStart.ts#L21)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

In my ignorance of all this, one thing that threw me for a long time is that we have two layers of long-running-ness. There are two long-running API calls (upload-start and upload-finish) and then the even longer-running process that happens in between, when we're uploading the files. I first came at this expecting that uploadStart was about initializing a long-running task called Upload, and uploadFinish was about when that long-running task was finished. But actually, each of them initiates a long-running task whose termination is detected by calling the status API. I think a comment on this function, and perhaps at least a cross-reference at the start of handleUploadFinish, would be very helpful for someone coming at this code the first time.
</blockquote></details>

See if the comments I've added scratch this itch. If not, I can try to expand them further.
___
*[`book/uploadStart.ts` line 106 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9KN_q7cgzkfueGWkh:-Nlio2A-59EYPeWn61Mv:b413y62) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/book/uploadStart.ts#L106)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Are you thinking that an earlier upload attempt failed, or trying to handle the case that the same account is trying to upload the same book from two computers at the same time?
I suppose what we're deleting is files in a holding area? We're not going to interfere with the previous upload until we have a complete one?
</blockquote></details>

Yes, it is basically a holding area until upload-finish changes the baseUrl to point to it.
Mostly this is for the previously-failed upload case.

There is also another cleanup function which runs daily to find and clean up such orphans.
___
*[`status/README.md` line 10 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-Nl9P3Uv2eca19KFAwy9:-Nlin-cW0SxxvtLcPTVi:b-hdb3ri) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/63603fd69237f03de062e665539411e35b53ab36/status/README.md#L10)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

These guidelines say "A long-running POST should not be used for resource create". Does that mean we should be using PUT instead of POST when a book is uploaded for the first time?
</blockquote></details>

I didn't feel like it fit our use case. But I admit I don't have an expert grasp on all this.
But to return from the initial response with a 201 Created just seems wrong when the record (while technically true is currently created) may be cleaned up (deleted) automatically if something bad happens.
My intuition is that the type of "resource" being created in their documentation is a different kind of thing than ours.

Another reason not to follow that pattern is it just complicates things. We would need to have client code be able to follow that pattern as well as the POST pattern.

**Review by andrew-polk — COMMENTED** [review]
Ready for another round.

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-:-NnAIFyyByPoEqRUMrco:b-9v85be)* status: 15 of 19 files reviewed, 5 unresolved discussions (waiting on @JohnThomson)

**Review by JohnThomson — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`longRunningActions/utils.ts` line 9 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-NnATxkY-0q2hLSSat3_:-NnATxkZD0ynnBGWEYiF:b-30sq4k) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/67d68e61e8686d86fa58d2e6f1b15f1ffcb12bd7/longRunningActions/utils.ts#L9)):*
> ```XML
> }
> 
> export async function startLongRunningAction(
> ```

Could you add a comment explaining what the returned string is (and is for)?

**Review by andrew-polk — COMMENTED** [review]
> Dismissed @JohnThomson from a discussion.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69)* status: 18 of 19 files reviewed, all discussions resolved (waiting on @JohnThomson)

___
*[`longRunningActions/utils.ts` line 9 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/69#-NnATxkY-0q2hLSSat3_:-NnAX36U67he39U18zD6:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/67d68e61e8686d86fa58d2e6f1b15f1ffcb12bd7/longRunningActions/utils.ts#L9)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Could you add a comment explaining what the returned string is (and is for)?
</blockquote></details>

Done.

**Pull request merged**
