### PR TITLE
BL-10661 OPDS:  Clean up, Add more <link>s, add more tests

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)* status: all files reviewed, 6 unresolved discussions (waiting on @hatton)

___
*[opds/bookEntry.test.ts, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3R5nBbL4cDufiUYV:-Mot3R5nBbL4cDufiUYW:b-qe3mjh) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L134)):*
> ```
> BloomPub
> ```
bloomPUB
___
*[opds/bookEntry.test.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot4HigAjcbPxsfzY6P:-Mot4HigAjcbPxsfzY6Q:b-382qok) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L146)):*
> ```
> should omit read online link if someone disabled that
> ```
Should this be 
`should give read online link if allowed`
like the others?
___
*[opds/bookentry.ts, line 227 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot2oWU1ugDmSxnjV86:-Mot2oWU1ugDmSxnjV87:bgxzk8t) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L227)):*
> ```
> ofer
> ```
offer

If you're making other changes
___
*[opds/bookentry.ts, line 243 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3NThE8mL6bm-U-eZ:-Mot3NThE8mL6bm-U-e_:b-qe3mjh) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L243)):*
> ```
> BloomPub
> ```
bloomPUB
___
*[opds/bookentry.ts, line 261 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot2UeH0ILhkrxDq6cN:-Mot2UeI1O9PUvUFOrM_:bghdl6m) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L261)):*
> ```
> https://bloomlibrary.org
> ```
${blorgRoot}
___
*[opds/opds.test.ts, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3Uej4y1cj8YlQXIu:-Mot3Uej4y1cj8YlQXIv:b-qe3mjh) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/opds.test.ts#L68)):*
> ```
> BloomPub
> ```
bloomPUB

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)* status: 3 of 7 files reviewed, 6 unresolved discussions (waiting on @andrew-polk)

___
*[opds/bookEntry.test.ts, line 134 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3R5nBbL4cDufiUYV:-Mp7pzrV-B0WTO0j4LZ1:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L134)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BloomPub
> ```
bloomPUB
</blockquote></details>

Done.
___
*[opds/bookEntry.test.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot4HigAjcbPxsfzY6P:-Mp7q8nE6nXuIcpNzg9N:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L146)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> should omit read online link if someone disabled that
> ```
Should this be 
`should give read online link if allowed`
like the others?
</blockquote></details>

Done.
___
*[opds/bookentry.ts, line 227 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot2oWU1ugDmSxnjV86:-Mp7qBex59mYAKQ910Xh:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L227)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> ofer
> ```
offer

If you're making other changes
</blockquote></details>

Done.
___
*[opds/bookentry.ts, line 243 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3NThE8mL6bm-U-eZ:-Mp7qC3v1EaGWOq3an6N:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L243)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BloomPub
> ```
bloomPUB
</blockquote></details>

Done.
___
*[opds/bookentry.ts, line 261 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot2UeH0ILhkrxDq6cN:-Mp7qYa1E0Ur5PVpK51I:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L261)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> https://bloomlibrary.org
> ```
${blorgRoot}
</blockquote></details>

Done.
___
*[opds/opds.test.ts, line 68 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mot3Uej4y1cj8YlQXIu:-Mp7qZTx9HTWRyncHvOZ:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/opds.test.ts#L68)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> BloomPub
> ```
bloomPUB
</blockquote></details>

Done.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)* status: all files reviewed, 1 unresolved discussion (waiting on @hatton)

___
*[opds/catalog.ts, line 18 at r2](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mp7rwo029yakakGZob7:-Mp7rwo029yakakGZob8:b4ykqib) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/9709bd3974e535659ff77ca1e112c2376cdcdabe/opds/catalog.ts#L18)):*
> ```XML
>   // point it should be fairly trivial to implement, following the pattern of ePUB.  This is just here as a
>   // placeholder to remind us what to do when the time comes.
>   // bloomPUB = "bloomPUB",
> ```

I think this line wants to be the way it was.
The first, all caps part is an enum value and the other values are all caps.
The second is part of the url (I think?) and the other values are all lowercase.

Of course, currently it is just a comment. So I'd be ok with you merging, especially since you have another change waiting on top of this. But I don't think we want to implement the real thing this way.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[opds/catalog.ts, line 18 at r2](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35#-Mp7rwo029yakakGZob7:-Mp7uZ2N65Q4p5DQXCMm:b2pyn9x) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/9709bd3974e535659ff77ca1e112c2376cdcdabe/opds/catalog.ts#L18)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I think this line wants to be the way it was.
The first, all caps part is an enum value and the other values are all caps.
The second is part of the url (I think?) and the other values are all lowercase.

Of course, currently it is just a comment. So I'd be ok with you merging, especially since you have another change waiting on top of this. But I don't think we want to implement the real thing this way.
</blockquote></details>

OK, fixed in next PR

**Review by andrew-polk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/35)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @hatton)

**Pull request merged**
