### PR TITLE
Implement book deletion (BL-12726)

### PR DESCRIPTION
**Pull request by andrew-polk**
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)

### CODE REVIEW

**Review by hatton — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`books/index.ts` line 232 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXwjdh0uOiyaXidFuI:-NtXwjdi3gdOV9M-Spvy:b-we8l49) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L232)):*
> ```XML
>         await BloomParseServer.isUploaderOrCollectionEditor(userInfo, bookInfo);
> 
>       let isModerator = false;
> ```

We probably want to remove the isModerator from most of this; it's redundant and makes it harder to assign permissions to a volunteer to work in certain areas. I feel like I keep making that claim but the code doesn't reflect it, so I'm assuming that the current moderator-can-do-anything is for a practical reason or some other reason that we don't actually want to make this change.

So in the meantime, can you add a comment saying why for now we're keeping it this way, as a way of recording what we're doing/plannning? Thx.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`books/index.ts` line 238 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXxyrC5wi5u4N2su-n:-NtXxyrC5wi5u4N2su-o:b2l5f34) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L238)):*
> ```XML
>       if (isUploaderOrCollectionEditor || isModerator) {
>         let superUserSessionToken = null;
>         if (!isModerator) {
> ```

I suppose the Parse permissions already say moderators are allowed to do things? A brief explanation of why this doesn't need superuser token might be helpful.

**Comment by andrew-polk** [comment]
*[`books/index.ts` line 232 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXwjdh0uOiyaXidFuI:-NtXzBed5e_fEqZfSkhI:b7xrtdx) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L232)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

We probably want to remove the isModerator from most of this; it's redundant and makes it harder to assign permissions to a volunteer to work in certain areas. I feel like I keep making that claim but the code doesn't reflect it, so I'm assuming that the current moderator-can-do-anything is for a practical reason or some other reason that we don't actually want to make this change.

So in the meantime, can you add a comment saying why for now we're keeping it this way, as a way of recording what we're doing/plannning? Thx.
</blockquote></details>

If we are ready to move away from moderator, I think now is as good a time as any.  
Two reasons I haven't done it yet:

1.  I wasn't sure we wanted to move away from it for all actions. If we do, great; that does simplify things.
2.  We haven't set people up in Contentful yet. But we can do that now if we're ready. I'll take a look at who are currently moderators.

**Comment by andrew-polk** [comment]
*[`books/index.ts` line 232 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXwjdh0uOiyaXidFuI:-NtY-50b5u1smLZ7s5G_:b-5xjfpo) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L232)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If we are ready to move away from moderator, I think now is as good a time as any.  
Two reasons I haven't done it yet:

1.  I wasn't sure we wanted to move away from it for all actions. If we do, great; that does simplify things.
2.  We haven't set people up in Contentful yet. But we can do that now if we're ready. I'll take a look at who are currently moderators.
</blockquote></details>

Actually, there are at least two ways moderator is helpful which the collection editor system doesn't give us currently:
1. bulk edit
2. staff panel

We could, in theory, make the "read.root" collection indicate moderator permissions. But technically, which collections you have permission on, and the level of permission should be orthogonal. Or current model doesn't allow for that if we get rid of moderator.

**Comment by andrew-polk** [comment]
*[`books/index.ts` line 238 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXxyrC5wi5u4N2su-n:-NtY3cBIEeZVU7teXYES:b-6puiu1) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L238)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I suppose the Parse permissions already say moderators are allowed to do things? A brief explanation of why this doesn't need superuser token might be helpful.
</blockquote></details>

Done.

I considered whether it was better to just use the super user every time.
It simplifies things a little. But it also means an unnecessary login for every action performed by a moderator or uploader.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`books/index.ts` line 232 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXwjdh0uOiyaXidFuI:-NtYKwbO-opUg95fh9z8:bx2lym6) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L232)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Actually, there are at least two ways moderator is helpful which the collection editor system doesn't give us currently:
1. bulk edit
2. staff panel

We could, in theory, make the "read.root" collection indicate moderator permissions. But technically, which collections you have permission on, and the level of permission should be orthogonal. Or current model doesn't allow for that if we get rid of moderator.
</blockquote></details>

So, bulk edit is a good example. Moderators can use it, but anything they try to do on a collection that they don't have permission on will fail. That's good. I can even imagine only giving myself temporary permission on collections that I intend to make bulk changes on.

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[`books/index.ts` line 238 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXxyrC5wi5u4N2su-n:-NtYLcGr5pjW3uY3-klj:b-4svkxs) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L238)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Done.

I considered whether it was better to just use the super user every time.
It simplifies things a little. But it also means an unnecessary login for every action performed by a moderator or uploader.
</blockquote></details>

What happens when bulk editing? DOes the log in happen over and over?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`books/index.ts` line 232 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXwjdh0uOiyaXidFuI:-NtqWmiE9IswZ9dg2qBK:b-gzweo6) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L232)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

So, bulk edit is a good example. Moderators can use it, but anything they try to do on a collection that they don't have permission on will fail. That's good. I can even imagine only giving myself temporary permission on collections that I intend to make bulk changes on.
</blockquote></details>

Decision from discussion this morning:
Moderator can do everything.

In the future, we may introduce a `librarian` role with permission level between editor and moderator at the collection level.
___
*[`books/index.ts` line 238 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-NtXxyrC5wi5u4N2su-n:-NtqX16b3HHeZC-VCNJy:b-yy7nc) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/d077e1179a454f5f00243da91649c95fc0ccfc8e/books/index.ts#L238)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

What happens when bulk editing? DOes the log in happen over and over?
</blockquote></details>

Currently, bulk editing doesn't use the API.
We had decided to put off book modification to after 5.7 is done.

But the blorg code does simply loop through each book and send an update for each. So if we didn't do something different, yes, it would log in again for each call.

**Review by JohnThomson — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 4 of 5 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-:-NtqsmFNAHgVilVdab4Q:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk and @hatton)

___
*[`books/index.ts` line 269 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-Ntqtl2y3du9sAuaizST:-Ntqtl2zCiqOuohjAMxT:b24vf9f) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/f17058f12ce9f62d0546c9f8b22b97808d2b58f1/books/index.ts#L269)):*
> ```XML
>     // Always return 204, even if the book wasn't found or the user didn't have permission.
>     // That's on the recommendation of https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md
>     // which we've generally been trying to follow.
> ```

I'm not seeing the second half. Not returning 404 for not-found makes sense; it's arguable that "Delete X" means "make sure X does not exist" and that has been done successfully. But I cannot see any argument that "Delete X" has succeeded when X exists and I am not allowed to delete it and so it has not been deleted.
In the guidelines I found
"**DO** return a `403-Forbidden` when the user does not have access to the resource _unless_ this would leak information about the existence of the resource that should not be revealed for security/privacy reasons, in which case the response should be `404-Not Found`. \[Rationale: a `403-Forbidden` is easier to debug for customers, but should not be used if even admitting the existence of things could potentially leak customer secrets.\]"

It's not completely clear that this applies to DELETE, but I think it makes sense for it to apply to everything.

Also puzzling: they say " **DO** return status code `202-Accepted` and follow the guidance in [Long-Running Operations & Jobs](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs) when a PUT, POST, or DELETE method completes asynchronously."
But also "**DO** return a `204-No Content` without a resource/body for a DELETE operation (even if the URL identifies a resource that does not exist; do not return `404-Not Found`)"

So the guidelines appear to me confusing, contradictory, and insufficiently justified. On one interpretation, you could find out whether a resource exists by trying to delete it and getting a 204 if it doesn't exist and a 404 if it does but you're not allowed to know that!

But I think a reasonable interpretation is 204 for success (deleted or already didn't exist) and 403 when it does exist but the user lacks permission to delete it (since we're not trying to hide the existence of anything from anyone).

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[`books/index.ts` line 269 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-Ntqtl2y3du9sAuaizST:-NtrFbOd-jQ0uvjsADNF:b-rym5nj) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/f17058f12ce9f62d0546c9f8b22b97808d2b58f1/books/index.ts#L269)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I'm not seeing the second half. Not returning 404 for not-found makes sense; it's arguable that "Delete X" means "make sure X does not exist" and that has been done successfully. But I cannot see any argument that "Delete X" has succeeded when X exists and I am not allowed to delete it and so it has not been deleted.
In the guidelines I found
"**DO** return a `403-Forbidden` when the user does not have access to the resource _unless_ this would leak information about the existence of the resource that should not be revealed for security/privacy reasons, in which case the response should be `404-Not Found`. \[Rationale: a `403-Forbidden` is easier to debug for customers, but should not be used if even admitting the existence of things could potentially leak customer secrets.\]"

It's not completely clear that this applies to DELETE, but I think it makes sense for it to apply to everything.

Also puzzling: they say " **DO** return status code `202-Accepted` and follow the guidance in [Long-Running Operations & Jobs](https://github.com/microsoft/api-guidelines/blob/vNext/azure/Guidelines.md#long-running-operations--jobs) when a PUT, POST, or DELETE method completes asynchronously."
But also "**DO** return a `204-No Content` without a resource/body for a DELETE operation (even if the URL identifies a resource that does not exist; do not return `404-Not Found`)"

So the guidelines appear to me confusing, contradictory, and insufficiently justified. On one interpretation, you could find out whether a resource exists by trying to delete it and getting a 204 if it doesn't exist and a 404 if it does but you're not allowed to know that!

But I think a reasonable interpretation is 204 for success (deleted or already didn't exist) and 403 when it does exist but the user lacks permission to delete it (since we're not trying to hide the existence of anything from anyone).
</blockquote></details>

Thanks; I was taking the simpler route on the idea of not exposing anything.
But I agree with your interpretation and made teh change.

(In my view, the asynchronous/long-running part doesn't apply here.)

**Review by JohnThomson — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/81#-:-NtrKrj0EojYckcllhGm:bnfp4nl)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @hatton)

**Pull request merged**
