### PR TITLE
Finish implementing books API (BL-12726)

### PR DESCRIPTION
**Pull request by andrew-polk**
Needs to be coordinated with BloomDesktop changes

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80)

### CODE REVIEW

**Review by JohnThomson — COMMENTED** [review]
Looks like good work. Most questions are minor.

> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-:-Nrgmxe-DMqImMGyQs6S:bvele3r)* status: all files reviewed, 7 unresolved discussions (waiting on @andrew-polk)

___
*[`books/index.ts` line 125 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgarYN5OvB1k7IY4c7:-NrgarYN5OvB1k7IY4c8:boderw4) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L125)):*
> ```XML
>   context.res = {
>     status: 200,
>     // Count isn't included if it is undefined (meaning the user didn't ask for it).
> ```

But we appear to be returning it unconditionally. I think you're saying that it will be undefined (or null or a meaningless zero?) if the user didn't ask for a count. But I wonder if it would be better to omit it altogether.
___
*[`books/index.ts` line 169 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgbTzI1GSo9wbk810o:-NrgbTzI1GSo9wbk810p:b-lbd6o5) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L169)):*
> ```XML
> }
> 
> async function handleGetOneBook(
> ```

How would anything use this safely, with no provision for restricting it to a single user, and no way to know whether there are other books with the same ID? Or is it somehow automatically restricted to the current user? I don't see anything checking that there even IS a logged-in user.
___
*[`books/parseAdapters.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-Nrgc4lG6B7t8TtUaIuC:-Nrgc4lG6B7t8TtUaIuD:b-u6v0sz) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/parseAdapters.ts#L3)):*
> ```XML
> // This file contains functions which sit in on the edge between the parse server and our books API.
> // They don't belong in BloomParseServer because they are only applicable to the books API.
> // But they contain code specific to parse server, so they deserve their own space.
> ```

Maybe not worth doing yet, but ideally we could break out the parse-specific code into an interface that defines exactly what some other backend must provide. But we'd need a bit more abstraction, and some more code pulled into this file...for example, the non-parse code should not know that API query params are being converted into Parse params, or that we are constructing a parse query at all.
Conversely, it feels to me as if the API code is more-or-less ALL about converting API calls into Parse queries and the results back into the shape we want, in which case, trying to break out the parse-specific code may be a losing battle. We just need to redo the API for whatever other backend we deploy.
___
*[`books/parseAdapters.ts` line 89 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgfXWIATKM3ScO4p_N:-NrgfXWIATKM3ScO4p_O:buolxj8) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/parseAdapters.ts#L89)):*
> ```XML
>   const expand = expandStr ? commaSeparatedStringToArray(expandStr) : [];
> 
>   const reshapedBook = { ...book } as any;
> ```

It's a hard call, but I wonder whether we want to return "everything else" by default or only the fields we explicitly decide to put in the api. It wouldn't be very hard to change the code below so that the input for each stage is book. Then here, just a couple of lines like

```
const {uploader, updateSource, inCirculation, harvestState, license} = book;
const reshapedBook = {uploader, updateSource, inCirculation, harvestState, license};
```

(It would be a longer list!) Or, if we can at least identify some things we definitely don't need to include, we could just delete those fields, so they can't be used by accident.

For example, it doesn't feel useful to return the ACL including the parse object ID of the user who is allowed to update the record. OTOH, there aren't many others that strike me as obviously not useful. After all, we have some use for them! We put them there. But it does add up to a lot of data most clients don't want.

There were reasons to put so much in the book table, I think mostly because parse doesn't handle 1:1 relations and queries involving both sides of them very well. And conversely it does seem to handle tables with lots of fields. But in a more powerful database it would possibly make sense that each book has a separate record in another table recording the results of harvesting it. (This record, for one thing, ought to be writeable only by our harvester, not by the user who uploaded the book.) And the record of which artifacts to show should also be in a different table, with different access rights (e.g., the uploading user should not be allowed to change the librarian's decision about whether to show an artifact). With such an architecture, we might well want a separate API to get information about the harvest state of a book, or which artifacts to show.
___
*[`common/BloomParseServer.ts` line 362 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-Nrgmkij1RuSA9DK0ib-:-Nrgmkij1RuSA9DK0ib0:b-rnoc4p) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L362)):*
> ```XML
>   public async getBook(
>     where: string,
>     fieldsToExpand: string[] = []
> ```

It's not obvious why this would not support additionalParams...except maybe we just haven't needed it yet?
___
*[`common/BloomParseServer.ts` line 410 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgjLsR3jZz_G4iriuH:-NrgjLsR3jZz_G4iriuI:b-tzh6td) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L410)):*
> ```XML
>         where,
>         include: fieldsToExpand.join(","),
>         ...additionalParams.reduce((acc, cur) => ({ ...acc, ...cur }), {}),
> ```

This is like flattening the array into a single object with all the fields of all the array members? Feels like it deserves a little explanation.
___
*[`common/BloomParseServer.ts` line 420 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgjjVK0jnv8zEsWL4b:-NrgjjVK0jnv8zEsWL4c:b50s9ip) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L420)):*
> ```XML
>   }
> 
>   public async getBookInfoByObjectId(
> ```

Aren't we trying to get away from the term 'objectId'? Should this be 'getBookByDatabaseId'?

**Review by andrew-polk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80)* status: 2 of 16 files reviewed, 7 unresolved discussions (waiting on @JohnThomson)

___
*[`books/index.ts` line 125 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgarYN5OvB1k7IY4c7:-NrgsM5E0bBFVbvY-Trx:b-sjtztn) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L125)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

But we appear to be returning it unconditionally. I think you're saying that it will be undefined (or null or a meaningless zero?) if the user didn't ask for a count. But I wonder if it would be better to omit it altogether.
</blockquote></details>

My experimenting indicated that if count is undefined, the prop is not included in the object at all.
I'll re-verify and try to improve my comment.
___
*[`books/index.ts` line 169 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgbTzI1GSo9wbk810o:-NrgoJzO7GSFoFVMVMQt:b-yxjxmh) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L169)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

How would anything use this safely, with no provision for restricting it to a single user, and no way to know whether there are other books with the same ID? Or is it somehow automatically restricted to the current user? I don't see anything checking that there even IS a logged-in user.
</blockquote></details>

This is for the /books/{id} endpoint where id is a database ID.
There is, intentionally, no security around that.
___
*[`books/parseAdapters.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-Nrgc4lG6B7t8TtUaIuC:-NrllYXb2us-TRWkh-x2:bsw7s4w) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/parseAdapters.ts#L3)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Maybe not worth doing yet, but ideally we could break out the parse-specific code into an interface that defines exactly what some other backend must provide. But we'd need a bit more abstraction, and some more code pulled into this file...for example, the non-parse code should not know that API query params are being converted into Parse params, or that we are constructing a parse query at all.
Conversely, it feels to me as if the API code is more-or-less ALL about converting API calls into Parse queries and the results back into the shape we want, in which case, trying to break out the parse-specific code may be a losing battle. We just need to redo the API for whatever other backend we deploy.
</blockquote></details>

Yeah, I do think it would be a losing battle and we would end up basically rewriting it.
___
*[`books/parseAdapters.ts` line 89 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgfXWIATKM3ScO4p_N:-NrlqwC6B09PULJUNTLT:bdhhcim) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/parseAdapters.ts#L89)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's a hard call, but I wonder whether we want to return "everything else" by default or only the fields we explicitly decide to put in the api. It wouldn't be very hard to change the code below so that the input for each stage is book. Then here, just a couple of lines like

```
const {uploader, updateSource, inCirculation, harvestState, license} = book;
const reshapedBook = {uploader, updateSource, inCirculation, harvestState, license};
```

(It would be a longer list!) Or, if we can at least identify some things we definitely don't need to include, we could just delete those fields, so they can't be used by accident.

For example, it doesn't feel useful to return the ACL including the parse object ID of the user who is allowed to update the record. OTOH, there aren't many others that strike me as obviously not useful. After all, we have some use for them! We put them there. But it does add up to a lot of data most clients don't want.

There were reasons to put so much in the book table, I think mostly because parse doesn't handle 1:1 relations and queries involving both sides of them very well. And conversely it does seem to handle tables with lots of fields. But in a more powerful database it would possibly make sense that each book has a separate record in another table recording the results of harvesting it. (This record, for one thing, ought to be writeable only by our harvester, not by the user who uploaded the book.) And the record of which artifacts to show should also be in a different table, with different access rights (e.g., the uploading user should not be allowed to change the librarian's decision about whether to show an artifact). With such an architecture, we might well want a separate API to get information about the harvest state of a book, or which artifacts to show.
</blockquote></details>

Yeah, a very hard call. But there are certainly quite a few fields we don't ever expect to return from the API.
I decided to whitelist for now. We can always revisit.
___
*[`common/BloomParseServer.ts` line 362 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-Nrgmkij1RuSA9DK0ib-:-Nrgs7HTCRtsknjjwmrW:b-w5fuef) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L362)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

It's not obvious why this would not support additionalParams...except maybe we just haven't needed it yet?
</blockquote></details>

They are things like `skip`, `limit`, `count`.
I'm not sure if there are any others. And I don't think those will ever apply to getting a single book.
___
*[`common/BloomParseServer.ts` line 410 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgjLsR3jZz_G4iriuH:-Nrgs64Y-D3-vc4jAxmn:bidb31l) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L410)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This is like flattening the array into a single object with all the fields of all the array members? Feels like it deserves a little explanation.
</blockquote></details>

Decided to simplify.
___
*[`common/BloomParseServer.ts` line 420 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgjjVK0jnv8zEsWL4b:-NrgpG8c9Mv14jSRRIRu:b-rokt7p) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/common/BloomParseServer.ts#L420)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Aren't we trying to get away from the term 'objectId'? Should this be 'getBookByDatabaseId'?
</blockquote></details>

You can't tell due to my refactoring... but this is an existing function.

Regardless... I'm double-minded. On the one hand, I certainly see your point. On the other hand, this is a parse-specific class.
I decided to change it on the vague idea that this could be an interface-exposed function if we had a well-architected backend we could swap out.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80)* status: 2 of 16 files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`books/index.ts` line 169 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgbTzI1GSo9wbk810o:-NrqjVeY0TaJo35A-n1k:bu52f89) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

This is for the /books/{id} endpoint where id is a database ID.
There is, intentionally, no security around that.
</blockquote></details>


Since I misunderstood completely and thought bookId meant bookInstanceId, maybe we should change it to databaseId? It's of course clear in the code (even more so now) but some users may just see the API documentation? Maybe even the function name should emphasize that somehow...or maybe this function is not in the API?
___
*[`books/parseAdapters.ts` line 3 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-Nrgc4lG6B7t8TtUaIuC:-NrqnSbeC2XwNzCoATzd:bvk79fl) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/parseAdapters.ts#L3)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Yeah, I do think it would be a losing battle and we would end up basically rewriting it.
</blockquote></details>

So then what does it mean to talk about functions specific to parse server deserving their own space (if more-or-less all the code is specific to parse server one way or another)?

**Review by JohnThomson — APPROVED** [review]
LGTM

> Reviewed 10 of 14 files at r2, 1 of 2 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-:-NruvR2xBMSAeq8Ns6Fo:bb6ywmx)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @andrew-polk)

___
*[`books/index.ts` line 169 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/80#-NrgbTzI1GSo9wbk810o:-Nruurd15881URo-5BFG:bufq52q) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/70fe50b9baba5a91bffdf248de524487d3df3298/books/index.ts#L169)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

The function isn't directly part of the public API.
But the endpoint it represents (/books/{id}) is.

I'm unsure how to best document it.
Currently, the API knows about "id" and "instanceId". I'm hesitant, even in a description, to label the "id" as a "database ID" since that is implementation detail and seems overly technical.
I could describe it as something like "The book's ID on BloomLibrary.org. e.g. a1bcdef234 in bloomlibrary.org/book/a1bcdef234." But that is also an implementation detail.

But here in the code, it does make sense to make the distinction which I've done now.
</blockquote></details>

I think that's sufficient. Thanks.

**Pull request merged**
