### PR TITLE
BL-10678 Add API Key

### PR DESCRIPTION
**Pull request by hatton**
This change is [Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36)

### CODE REVIEW

**Review by JohnThomson — APPROVED** [review]
Few minor points. I'm not familiar enough with this code to be confident that everything that got deleted was replaced with something appropriate, but the new logic makes sense.
I don't think anything I've commented MUST be done, so feel free to merge after fixing whatever you think is worth it.

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-:-Mp8O-2o-35ZH_L1ZKJC:bp3y4f6)* status: 3 of 15 files reviewed, 6 unresolved discussions (waiting on @hatton and @JohnThomson)

___
*[opds/bookEntry.test.ts, line 89 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8I4Zu9NO8fTHbqwSf:-Mp8I4Zu9NO8fTHbqwSg:b40cfxw) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L89)):*
> ```XML
>         objectId: "0YpcRpEw66",
>         id: "",
>         username: "joeucag@yahoo.com",
> ```

Looks like a real email. Is it likely to get scraped from git? Or could there be a risk one day of unit tests sending him messages? Might be better to use something fake. Of course maybe the test requires a real user.
___
*[opds/bookEntry.test.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8KPGL6S3f1O25GBkq:-Mp8KPGL6S3f1O25GBkr:b7ikok2) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L146)):*
> ```XML
>   });
> 
>   it("should omit read online link if someone disabled that", () => {
> ```

This comment is not parallel to the others, but all testArtifactLink calls test this kind of disabling.
___
*[opds/bookEntry.test.ts, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8Jf3j08BcYUqwy1h9:-Mp8Jf3j08BcYUqwy1hA:bbsewvl) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L179)):*
> ```XML
> 
>   // if the user turns it off, don't offer it
>   book.show[artifactName].user = false;
> ```

Would be a stronger test with both harvester and librarian saying to show it. (I think both are undefined at this point?)
___
*[opds/bookEntry.test.ts, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8K6Z1CrDCJo6x3UeX:-Mp8K6Z1CrDCJo6x3UeY:b-8k87u3) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L205)):*
> ```XML
> 
>   // enhance: we could test other combinations. The `bookEntry.shouldWePublishArtifact()` code that implements
>   // this logic is pretty simple, however, so I'm not highly motivated to test each combination.
> ```

Seems like you should test at least one combination where the link IS shown even when shouldHaveLinkIfEverythingUndefined is false.
___
*[opds/bookentry.ts, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8LREb7h8-7w_Pcj0n:-Mp8LREb7h8-7w_Pcj0o:bc87tqt) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L101)):*
> ```XML
>     }
>     entry += links;
>     return entry + `</entry>`;
> ```

I don't think it matters in this context, but as long as I'm commenting...did you mean to leave out the space that the old code had before the closing tag?
___
*[opds/bookentry.ts, line 244 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8MbUBE_7eNY4fIz5a:-Mp8MbUBE_7eNY4fIz5b:b-ypr2au) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L244)):*
> ```XML
>         links += BookEntry.makeLink(
>           "BloomPub",
>           `${harvestBaseUrl}/${name}.bloomd`,
> ```

Worth making a constant for this extension? Sometime, maybe soon, we want to change them to bloompub.

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, 4 of 4 files at r2, 11 of 11 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36)* status: all files reviewed, 11 unresolved discussions (waiting on @hatton)

___
*[opds/catalog.ts, line 91 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7v0Bf5BhtZdPkONNK:-Mp7v0Bf5BhtZdPkONNL:b7s4k50) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/catalog.ts#L91)):*
> ```XML
>       ? apiAccount.embargoDays + " wait"
>       : ""
>   }  -->
> ```

Maybe a comment stating if this is planned to be added or just for debugging?

Related, apiAccount is not currently used even though it is a newly added parameter of getCatalog
___
*[opds/catalog.ts, line 19 at r4](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp9152403B53q19koaM:-Mp9152403B53q19koaN:b-by89eg) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/6840ee92fc316a438b7f15e5034a92fa23c6e3f7/opds/catalog.ts#L19)):*
> ```
> bloomPUB
> ```
If I'm not wrong, this is part of the url and we want it, when implemented, to be all lowercase like the others.
___
*[opds/catalog.ts, line 115 at r4](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp91DV3B6v_AhKBQIWI:-Mp91DV3B6v_AhKBQIWJ:bvryc9w) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/6840ee92fc316a438b7f15e5034a92fa23c6e3f7/opds/catalog.ts#L115)):*
> ```
> <link rel="up" href="${Catalog.RootUrl}" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
> ```
This line got duplicated.
___
*[opds/README.md, line 58 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7tzFb1X1A7_4aZ_n_:-Mp7tzFb1X1A7_4aZ_na:b-8d7wb9) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/README.md#L58)):*
> ```
> colo
> ```
colon
___
*[opds/README.md, line 64 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7txKk5YljeOJGI3GR:-Mp7txKk5YljeOJGI3GS:b-8bd96c) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/README.md#L64)):*
> ```
> For example, consider the following URL sent to the function:
> ```
extraneous line

**Review by hatton — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36)* status: 9 of 15 files reviewed, 11 unresolved discussions (waiting on @andrew-polk and @JohnThomson)

___
*[opds/bookEntry.test.ts, line 89 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8I4Zu9NO8fTHbqwSf:-MpC6wqW5TPf9K3cfWk6:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L89)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Looks like a real email. Is it likely to get scraped from git? Or could there be a risk one day of unit tests sending him messages? Might be better to use something fake. Of course maybe the test requires a real user.
</blockquote></details>

Done.
___
*[opds/bookEntry.test.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8KPGL6S3f1O25GBkq:-MpC7JFn2rfBZyedYNlr:b-tpdq3j) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L146)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

This comment is not parallel to the others, but all testArtifactLink calls test this kind of disabling.
</blockquote></details>

Sorry, I don't understand what you're saying. 
___
*[opds/bookEntry.test.ts, line 179 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8Jf3j08BcYUqwy1h9:-MpC7wnr1ANnwlSgbCQ1:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L179)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Would be a stronger test with both harvester and librarian saying to show it. (I think both are undefined at this point?)
</blockquote></details>

Done.
___
*[opds/bookEntry.test.ts, line 205 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8K6Z1CrDCJo6x3UeX:-MpC8p5cBfT8ZVhHlxMY:bu69t9e) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L205)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Seems like you should test at least one combination where the link IS shown even when shouldHaveLinkIfEverythingUndefined is false.
</blockquote></details>

There is, in the first set of `expect`s in this method.
___
*[opds/bookentry.ts, line 101 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8LREb7h8-7w_Pcj0n:-MpC9-ae-6x1lPdCE-Ff:b-5bpi96) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L101)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I don't think it matters in this context, but as long as I'm commenting...did you mean to leave out the space that the old code had before the closing tag?
</blockquote></details>

The old code was complicated by trying to make the output pretty. But it's just xml, the browser already formats it.
___
*[opds/bookentry.ts, line 244 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8MbUBE_7eNY4fIz5a:-MpC9HtJCnKsexcvD-Zn:b-eq7z8o) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookentry.ts#L244)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

Worth making a constant for this extension? Sometime, maybe soon, we want to change them to bloompub.
</blockquote></details>

then we'll change it.
___
*[opds/catalog.ts, line 91 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7v0Bf5BhtZdPkONNK:-MpCAJRb91f7XVGlh5lG:b-igzy0g) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/catalog.ts#L91)):*
Neither. It's the output I want.

> Related, apiAccount is not currently used even though it is a newly added parameter of getCatalog

One PR at a time, my fried.
___
*[opds/catalog.ts, line 19 at r4](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp9152403B53q19koaM:-MpC9ypSAlswLvGnvbrd:b-p5g486) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/6840ee92fc316a438b7f15e5034a92fa23c6e3f7/opds/catalog.ts#L19)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> bloomPUB
> ```
If I'm not wrong, this is part of the url and we want it, when implemented, to be all lowercase like the others.
</blockquote></details>

It's just an enum tag, right? And in a comment? 
___
*[opds/catalog.ts, line 115 at r4](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp91DV3B6v_AhKBQIWI:-MpCAd00-NmYtoDTkUZT:b2nid0f) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/6840ee92fc316a438b7f15e5034a92fa23c6e3f7/opds/catalog.ts#L115)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> <link rel="up" href="${Catalog.RootUrl}" type="application/atom+xml;profile=opds-catalog;kind=navigation"/>
> ```
This line got duplicated.
</blockquote></details>

thx
___
*[opds/README.md, line 58 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7tzFb1X1A7_4aZ_n_:-MpCAkxE1bBgWPYH2uVn:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/README.md#L58)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> colo
> ```
colon
</blockquote></details>

Done.
___
*[opds/README.md, line 64 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7txKk5YljeOJGI3GR:-MpCAoOMDpHrTUySyj63:b-896fix) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/README.md#L64)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

> ```
> For example, consider the following URL sent to the function:
> ```
extraneous line
</blockquote></details>

Done.

**Review by andrew-polk — APPROVED** [review]
> Reviewed 6 of 6 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36)* status: all files reviewed, 6 unresolved discussions (waiting on @JohnThomson)

___
*[opds/bookEntry.test.ts, line 146 at r1](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp8KPGL6S3f1O25GBkq:-MpCDd0p9Wo-zcqkY6rU:b-om8ear) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/02d1adb5e6a30f1072f64b9dad9107aae7b14e44/opds/bookEntry.test.ts#L146)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Sorry, I don't understand what you're saying. 
</blockquote></details>

I think the comment was based on the first version of that test name which was subsequently changed.
___
*[opds/catalog.ts, line 91 at r3](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp7v0Bf5BhtZdPkONNK:-MpCEH8REt6YI1-X3mVn:b-utiti5) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/7f0da313ab0aa856c1c1c1f8ba7b6b22fa7a56cd/opds/catalog.ts#L91)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

Neither. It's the output I want.

> Related, apiAccount is not currently used even though it is a newly added parameter of getCatalog

One PR at a time, my fried.
</blockquote></details>

Sorry; I totally misread this part of the code thinking it was a comment in the code rather than a comment being added to the output.
Egg on my face.
___
*[opds/catalog.ts, line 19 at r4](https://reviewable.io/reviews/bloombooks/bloom-azure-functions/36#-Mp9152403B53q19koaM:-MpCEzlu3eMqy_Z2dpvp:b-pej5fm) ([raw file](https://github.com/bloombooks/bloom-azure-functions/blob/6840ee92fc316a438b7f15e5034a92fa23c6e3f7/opds/catalog.ts#L19)):*
<details><summary><i>Previously, hatton (John Hatton) wrote…</i></summary><blockquote>

It's just an enum tag, right? And in a comment? 
</blockquote></details>

Comment yes, but one a line we intend to uncomment and in my view, the change you've made to the comment is going from correct to incorrect.

Regardless, I thought the "bloomPUB" string made it as is into the output, but that doesn't appear to be the case. Sorry.

**Pull request merged**
