### PR TITLE
BL-12759 add book get language object id

### PR DESCRIPTION
**Pull request by nabalone**
Hide Parse behind API: Upload

- - -
This change is [Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)

### CODE REVIEW

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: all files reviewed, 3 unresolved discussions (waiting on @nabalone)

___
*[`book/index.ts` line 54 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipqbr93JQ-cIRmg2qv:-Nipqbr93JQ-cIRmg2qw:b-8c674a) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L54)):*
> ```XML
>   env: Environment
> ) {
>   if (req.method !== "POST") {
> ```

Please add a comment explaining that this is a POST because we create the record if it doesn't exist.

Is there a better name for the action which would indicate that?
Do we want to go all the way to get-or-create-language-object-id?

Did you consider simply get-{or-create}-language and returning json instead of just an id? 
It has the advantage of a simpler name and the option to expand the data later if desired. 
But it might be yagni.
___
*[`book/index.ts` line 62 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-NiprsjL4FtHC48UfLcY:-NiprsjMBDxdZBU9im2A:b-mw1z84) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L62)):*
> ```XML
>   }
>   BloomParseServer.setServer(env);
>   const langJson = req.body;
> ```

What does req.body require? We need to document that somewhere.
Do we need to validate the input? Since you're just passing it through, maybe not?
___
*[`common/BloomParseServer.ts` line 270 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipsuqb6-YTNMJSh59F:-Nipsuqb6-YTNMJSh59G:b9nn9yc) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/common/BloomParseServer.ts#L270)):*
> ```XML
> 
>   public static getLanguage(langJson: any): Promise<any> {
>     return new Promise<any[]>((resolve, reject) =>
> ```

Does this need to use the Promise syntax? Can it use async await like the others?

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: all files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`book/index.ts` line 54 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipqbr93JQ-cIRmg2qv:-NipxPoN4S01vUaPOJlo:b-lgl8ot) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L54)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Please add a comment explaining that this is a POST because we create the record if it doesn't exist.

Is there a better name for the action which would indicate that?
Do we want to go all the way to get-or-create-language-object-id?

Did you consider simply get-{or-create}-language and returning json instead of just an id? 
It has the advantage of a simpler name and the option to expand the data later if desired. 
But it might be yagni.
</blockquote></details>

I really like the simpler name. Though this would (occasionally) require an additional database call because after creating the language we would have to get the langauge we just created. But I'm guessing we are rarely creating new language entries so this is fine?

**Comment by andrew-polk** [comment]
*[`book/index.ts` line 54 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipqbr93JQ-cIRmg2qv:-NiuMbj_6RHspqXQchQi:bxpjpk8) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L54)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

I really like the simpler name. Though this would (occasionally) require an additional database call because after creating the language we would have to get the langauge we just created. But I'm guessing we are rarely creating new language entries so this is fine?
</blockquote></details>

Sorry; I may have been unclear. I'm not suggesting switching to two calls.

Rather, we may want the name to reflect the fact that sometimes we are not only getting but also creating.

And then separately wondering if we want to simplify the name to omit `-object-id`. If we did, maybe it makes sense to return a json object instead of just the ID. Then, we could expand what we return in the future to include more info than just the ID.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`book/index.ts` line 54 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipqbr93JQ-cIRmg2qv:-NiuPHXx-k2DgojHtUn_:bmns19x) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L54)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Sorry; I may have been unclear. I'm not suggesting switching to two calls.

Rather, we may want the name to reflect the fact that sometimes we are not only getting but also creating.

And then separately wondering if we want to simplify the name to omit `-object-id`. If we did, maybe it makes sense to return a json object instead of just the ID. Then, we could expand what we return in the future to include more info than just the ID.
</blockquote></details>

Sounds good, how's this?
___
*[`book/index.ts` line 62 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-NiprsjL4FtHC48UfLcY:-NiutOVGDW-wYZV_Gvsv:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L62)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

What does req.body require? We need to document that somewhere.
Do we need to validate the input? Since you're just passing it through, maybe not?
</blockquote></details>

Done.
___
*[`common/BloomParseServer.ts` line 270 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipsuqb6-YTNMJSh59F:-Niuth1S8EQ964XczmPI:bs7wumb) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/common/BloomParseServer.ts#L270)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Does this need to use the Promise syntax? Can it use async await like the others?
</blockquote></details>

Done.

**Review by nabalone — COMMENTED** [review]
More changes coming based on Andrew's comments on my BloomDesktop PR

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-:-Niuw2JQEhIK_1yHno2h:b-jtj7dz)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: all files reviewed, 1 unresolved discussion (waiting on @nabalone)

___
*[`book/index.ts` line 54 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipqbr93JQ-cIRmg2qv:-NivI-bT3QLwMj1_7oaI:b-g2hy27) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/book/index.ts#L54)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Sounds good, how's this?
</blockquote></details>

Good. Thanks.
___
*[`common/BloomParseServer.ts` line 270 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipsuqb6-YTNMJSh59F:-NivIAsmDYF5Vte-FpC5:bbd845g) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/common/BloomParseServer.ts#L270)):*
<details><summary><i>Previously, nabalone (Noel) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Still seeing promises. Maybe something didn't get fully committed?

Oh. I see you changed getLanguages. That's good, too. But let's change this one if possible.

**Review by nabalone — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: 0 of 4 files reviewed, 3 unresolved discussions (waiting on @andrew-polk)

___
*[`book/uploadFinish.ts` line 89 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-NjDUuM06Btyhr1_yhKb:-NjEYv4t0n4HjHHYFYpu:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/8b0f684ea41f8ea685db192d25c4adec192bfec5/book/uploadFinish.ts#L89)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

I'm wondering what, if anything, we want/need to do about the fact that there will be a short time between when my and your BloomDesktop changes land.
I think we either need to merge both changes at basically the same time, or we need to allow for book records to come here with either langPointers or languageDescriptions.


After discussion just now, we decided on a simple if statement to determine if we have languageDescriptors, use them. Else just use the langPointers provided.
Then we are free to merge things as we wish.
</blockquote></details>

Done.
___
*[`common/BloomParseServer.ts` line 270 at r1](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-Nipsuqb6-YTNMJSh59F:-NjEZ5sR9xQiwunb-JzR:b-9hpyck) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/436f4ef068a0f14d386560f6a120d4394b5db8c8/common/BloomParseServer.ts#L270)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Still seeing promises. Maybe something didn't get fully committed?

Oh. I see you changed getLanguages. That's good, too. But let's change this one if possible.
</blockquote></details>

Oops. Done
___
*[`common/BloomParseServer.ts` line 250 at r3](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-NjDVZ4g-mpJ2NO2J9Rp:-NjEYvugAfc74BnnMEYQ:b-896fix) ([raw file](https://github.com/BloomBooks/bloom-azure-functions/blob/8b0f684ea41f8ea685db192d25c4adec192bfec5/common/BloomParseServer.ts#L250)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

Let's add return types for these new methods. And a brief comment explaining what it returns.
</blockquote></details>

Done.

**Review by andrew-polk — COMMENTED** [review]
Any unit tests we can reasonably add?

> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-:-NjEmmSM1LAiFCI4_D8F:b-fthv1w)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Review by andrew-polk — COMMENTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Review by nabalone — COMMENTED** [review]
Added one

> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65#-:-NjOqKry6Uo8P7vFEAS0:bqvwrsx)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @andrew-polk)

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/BloomBooks/bloom-azure-functions/65)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @nabalone)

**Pull request merged**
